### ISSUE TITLE
feature: CodeCommit Discovery

### ISSUE THREAD

**Issue by stijnbrouwers** [awslabs/backstage-plugins-for-aws#13]
### 🔖 Feature description

Discover entities on CodeCommit repositories similar to the [AwsS3DiscoveryProcessor](https://github.com/backstage/backstage/blob/master/plugins/catalog-backend-module-aws/src/processors/AwsS3DiscoveryProcessor.ts).

### 🎤 Context

As discussed first in #6

**Comment by niallthomson** [comment]
@stijnbrouwers do you feel this is addressed by the contribution you made upstream?

**Comment by stijnbrouwers** [comment]
@niallthomson 
No, discovery is not yet implemented in the contribution.
This is still a TODO at this point.

**Comment by niallthomson** [comment]
After looking in a bit more detail I see the gap here. I think we could do with outlining some more concrete requirements.

This is an example of configuring the GitHub equivalent:

```yaml
catalog:
  providers:
    github:
      # the provider ID can be any camelCase string
      providerId:
        organization: 'backstage' # string
        catalogPath: '/catalog-info.yaml' # string
        filters:
          branch: 'main' # string
          repository: '.*' # Regex
        schedule: # same options as in TaskScheduleDefinition
          # supports cron, ISO duration, "human duration" as used in code
          frequency: { minutes: 30 }
          # supports ISO duration, "human duration" as used in code
          timeout: { minutes: 3 }
```

I assume we'd need to take something like that format and add AWS considerations like how accounts and regions are handled. 

The simple approach would be that instead of the `organization` field each provider could accept optional `accountId` and `region` fields. However I would see obvious issues with this scaling in situations where CodeCommit repositories are spread across a large number of accounts in an AWS organization, so perhaps some discovery in that regard may also be necessary.
