### ISSUE TITLE
feature: support OpenAI compatible APIs in aws-genai plugin

### ISSUE THREAD

**Issue by vmahe35** [awslabs/backstage-plugins-for-aws#316]
### 🔖 Feature description

I suggest to add a new `langgraph.openai.baseUrl` parameter in the settings of the `aws-genai` plugin, that would look like this:

```yaml
genai:
  agents:
    general: # This matches the URL in the frontend
      description: ...
      prompt: ...
      langgraph:
        openai:
          baseUrl: ${OPENAI_API_BASE_URL}
          apiKey: ${OPENAI_API_KEY}
          modelName: ${QUERY_MODEL_NAME}
```

### 🎤 Context

OpenAI APIs have become a de-facto standard for many AI frameworks and many people today also use Ollama to facilitate the management of models as a Service. 
Ollama provides its own API but also has an [OpenAI compatible interface](https://github.com/ollama/ollama/blob/main/docs/openai.md).

Therefore, it would make sense to be able to configure another baseURL parameter for the endpoints than the default OpenAI endpoint (<https://api.openai.com/v1>).

### ✌️ Possible Implementation

I will submit a PullRequest for it (already developed and tested on my local dev env).
