### ISSUE TITLE
feature: Response caching

### ISSUE THREAD

**Issue by niallthomson** [awslabs/backstage-plugins-for-aws#328]
### 🔖 Feature description

For many plugins it would be good to have some sort of response caching to enable faster response times and less calls to the AWS APIs. This should be implemented consistently across plugins, providing an opportunity to enable/disable and specific a TTL for each plugin.

```yaml
aws:
  ecs:
    caching:
      enable: true
      ttl: 360
  codepipeline:
    caching:
      enable: true
      ttl: 60
```

Caching should always be disabled by default to avoid confusion.

This caching will have to take in to account RBAC considerations, for example if a user tries to access information related to a catalog entry that they do not have permissions to view.

### 🎤 Context

N/A
