### ISSUE TITLE
support: GenAI embedding tech docs

### ISSUE THREAD

**Issue by tommy04062019** [awslabs/backstage-plugins-for-aws#366]
I created a documentation file for one of my catalog entities and tried querying its content using GenAI. However, it seems GenAI hasn’t picked up the latest changes — it’s unable to find anything related to the new document.

Do I need to restart the Backstage instance or is there an API I can call to manually trigger a re-index or re-embedding of the updated documentation?

**Comment by tommy04062019** [comment]
> Hi [@tommy04062019](https://github.com/tommy04062019) is this using the catalog search integration?



> Hi [@tommy04062019](https://github.com/tommy04062019) is this using the catalog search integration?

Yes, this is, And I got an error like this:

<img width="1325" alt="Image" src="https://github.com/user-attachments/assets/1606b33c-dcde-4dbc-aa42-eb1a1e4fdf86" />

**Comment by niallthomson** [comment]
I believe by default the search index is updated every 10 minutes through the Backstage scheduler https://github.com/backstage/backstage/blob/master/plugins/search-backend-module-catalog/src/collators/config.ts#L27-L38

**Comment by tommy04062019** [comment]
> I believe by default the search index is updated every 10 minutes through the Backstage scheduler https://github.com/backstage/backstage/blob/master/plugins/search-backend-module-catalog/src/collators/config.ts#L27-L38

@niallthomson Okie, but what about the error above? I ran some days, and I still cannot to ask some contents in tech docs.  is it related to the size of tech docs?

**Comment by tommy04062019** [comment]
> What LLM are you using?

Here is my current config:
```
genai:
  agents:
    general: # This matches the URL in the frontend
      description: General chat assistant
      prompt: >
        <PROMPT>

      langgraph:
        messagesMaxTokens: 150000 # Set based on context of chosen model, prune message history based on number of tokens
        # Use appropriate snippet for your model provider
        # trimMessages: true
        openai:
          apiKey: sk-proj-xxxx
          modelName: gpt-4o
      tools:
        - backstageCatalogSearch
        - backstageEntity
        - backstageTechDocsSearch
        - urlDataFetch
```
