### ISSUE TITLE
Cross Account fetch for resources in ECS

### ISSUE THREAD

**Issue by Alok650** [awslabs/backstage-plugins-for-aws#78]
### 🔖 Feature description

Hi
We have integrated the ecs plugin in our backstage app. We use multiple aws accounts and I want to fetch ECS clusters and services from all the aws environments defined in integrations.aws (yaml list) and search through all these accounts. This would involve change the auth mechanism with Sts assume and assuming into cross account roles using temp credentials of the cross-account roles.

Endgoal is to display all clusters and ecs services having the defined set of tags (annotations.value)

### 🎤 Context

Have provided context above.

**Comment by niallthomson** [comment]
Hi @Alok650 this should currently be possible but the docs are still being finished.

There's a couple of options we're going to provide. How many AWS accounts will you be looking across?

**Comment by Alok650** [comment]
Hey @niallthomson 
It would be 5+ accounts i.e. I have defined it in integrations.aws, would could configure to use that as other AWS plugins also use it.

**Comment by niallthomson** [comment]
Do you happen to use AWS Config today?

**Comment by Alok650** [comment]
Hey @niallthomson Yes. I am using this. I am also using AWS plugins by roadie. You can refer those plugins as well

**Comment by Alok650** [comment]
Hi @niallthomson
is there a timeline on when cross-account related changes + Documentation would be released?

**Comment by niallthomson** [comment]
Hey @Alok650 this is something I'm working on right now. I'll have some idea of timing soon.

**Comment by niallthomson** [comment]
@Alok650 I've opened PR #85 to address this. It adds new configuration to use it, something like this:

```yaml
aws:
  locator:
    resourceTaggingApi:
      # Add each AWS account you wish to search
      accounts:
        - '1111111111'
        - '2222222222'
      # Add each AWS region you wish to search
      regions:
        - us-east-1
        - eu-west-2
```

I didn't want to rely on the authentication configuration since you can support multiple accounts with something like this:

```yaml
aws:
  accountDefaults:
    roleName: 'my-backstage-role'
```

Which is more efficient than adding each account individually.
